<a href="https://colab.research.google.com/github/Maansi-1590/Nutrition-Paradox/blob/main/Nutrition_Paradox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests

url="https://ghoapi.azureedge.net/api/NCD_BMI_30C"


response=requests.get(url)

data = response.json()

In [ ]:
data.keys()

dict_keys(['@odata.context', 'value'])

In [ ]:
import pandas as pd
df = pd.DataFrame(data['value'])

df.head()

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,ParentLocationCode,ParentLocation,Dim1Type,Dim1,TimeDim,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,664949,NCD_BMI_30C,COUNTRY,MLI,YEAR,AFR,Africa,SEX,SEX_MLE,2000,...,None,2.6 [1.7-3.9],2.628228,1.660743,3.912387,None,2024-02-29T16:06:41.017+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
1,664983,NCD_BMI_30C,COUNTRY,NLD,YEAR,EUR,Europe,SEX,SEX_FMLE,2015,...,None,16.9 [14.4-19.5],16.857454,14.449173,19.508865,None,2024-02-29T16:06:41.017+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
2,665462,NCD_BMI_30C,COUNTRY,LTU,YEAR,EUR,Europe,SEX,SEX_FMLE,2001,...,None,26.7 [24.4-29.0],26.669315,24.445811,28.968024,None,2024-02-29T16:06:41.017+01:00,2001,2001-01-01T00:00:00+01:00,2001-12-31T00:00:00+01:00
3,666740,NCD_BMI_30C,COUNTRY,COD,YEAR,AFR,Africa,SEX,SEX_BTSX,1996,...,None,1.6 [1.2-2.1],1.558140,1.155278,2.052579,None,2024-02-29T16:06:41.017+01:00,1996,1996-01-01T00:00:00+01:00,1996-12-31T00:00:00+01:00
4,667212,NCD_BMI_30C,COUNTRY,SWZ,YEAR,AFR,Africa,SEX,SEX_BTSX,2014,...,None,20.7 [18.8-22.6],20.660561,18.764348,22.622967,None,2024-02-29T16:06:41.017+01:00,2014,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00

In [ ]:
df['TimeDim'].value_counts()

TimeDim
2000    630
2015    630
2001    630
1996    630
2014    630
2007    630
2021    630
1994    630
2008    630
1998    630
1995    630
2002    630
1991    630
2020    630
1993    630
2012    630
2006    630
2004    630
2022    630
2010    630
1992    630
2018    630
2009    630
1990    630
2011    630
2003    630
2017    630
2013    630
1999    630
2016    630
1997    630
2005    630
2019    630
Name: count, dtype: int64

In [ ]:
df.shape

(20790, 25)

In [ ]:
df['age_group'] = "adults"

In [ ]:
df.head()

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,ParentLocationCode,ParentLocation,Dim1Type,Dim1,TimeDim,...,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd,age_group
0,664949,NCD_BMI_30C,COUNTRY,MLI,YEAR,AFR,Africa,SEX,SEX_MLE,2000,...,2.6 [1.7-3.9],2.628228,1.660743,3.912387,None,2024-02-29T16:06:41.017+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00,adults
1,664983,NCD_BMI_30C,COUNTRY,NLD,YEAR,EUR,Europe,SEX,SEX_FMLE,2015,...,16.9 [14.4-19.5],16.857454,14.449173,19.508865,None,2024-02-29T16:06:41.017+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00,adults
2,665462,NCD_BMI_30C,COUNTRY,LTU,YEAR,EUR,Europe,SEX,SEX_FMLE,2001,...,26.7 [24.4-29.0],26.669315,24.445811,28.968024,None,2024-02-29T16:06:41.017+01:00,2001,2001-01-01T00:00:00+01:00,2001-12-31T00:00:00+01:00,adults
3,666740,NCD_BMI_30C,COUNTRY,COD,YEAR,AFR,Africa,SEX,SEX_BTSX,1996,...,1.6 [1.2-2.1],1.558140,1.155278,2.052579,None,2024-02-29T16:06:41.017+01:00,1996,1996-01-01T00:00:00+01:00,1996-12-31T00:00:00+01:00,adults
4,667212,NCD_BMI_30C,COUNTRY,SWZ,YEAR,AFR,Africa,SEX,SEX_BTSX,2014,...,20.7 [18.8-22.6],20.660561,18.764348,22.622967,None,2024-02-29T16:06:41.017+01:00,2014,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00,adults

In [ ]:
import requests

url="https://ghoapi.azureedge.net/api/NCD_BMI_PLUS2C"

response=requests.get(url)

data=response.json()

In [ ]:
data.keys()

dict_keys(['@odata.context', 'value'])

In [ ]:
import pandas as pd
df = pd.DataFrame(data['value'])

df.head()

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,ParentLocationCode,ParentLocation,Dim1Type,TimeDim,Dim1,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,664972,NCD_BMI_PLUS2C,COUNTRY,FIN,YEAR,EUR,Europe,SEX,1993,SEX_FMLE,...,None,2.9 [1.6-4.6],2.926208,1.606209,4.626733,None,2024-02-29T16:06:41.017+01:00,1993,1993-01-01T00:00:00+01:00,1993-12-31T00:00:00+01:00
1,665160,NCD_BMI_PLUS2C,COUNTRY,TUR,YEAR,EUR,Europe,SEX,2008,SEX_MLE,...,None,8.7 [5.5-12.7],8.704282,5.491283,12.714332,None,2024-02-29T16:06:41.017+01:00,2008,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00
2,665226,NCD_BMI_PLUS2C,COUNTRY,GHA,YEAR,AFR,Africa,SEX,2013,SEX_FMLE,...,None,4.3 [3.1-5.6],4.291492,3.121873,5.612285,None,2024-02-29T16:06:41.017+01:00,2013,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00
3,665505,NCD_BMI_PLUS2C,COUNTRY,CIV,YEAR,AFR,Africa,SEX,2011,SEX_FMLE,...,None,2.6 [0.6-7.0],2.632850,0.577861,6.967106,None,2024-02-29T16:06:41.017+01:00,2011,2011-01-01T00:00:00+01:00,2011-12-31T00:00:00+01:00
4,665861,NCD_BMI_PLUS2C,GLOBAL,GLOBAL,YEAR,None,None,SEX,2008,SEX_FMLE,...,None,4.7 [4.4-5.0],4.700040,4.443568,4.981692,None,2024-05-23T13:28:38.2+02:00,2008,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00

In [ ]:
df['age_groups']= "children"

In [ ]:
df.head()

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,ParentLocationCode,ParentLocation,Dim1Type,TimeDim,Dim1,...,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd,age_groups
0,664972,NCD_BMI_PLUS2C,COUNTRY,FIN,YEAR,EUR,Europe,SEX,1993,SEX_FMLE,...,2.9 [1.6-4.6],2.926208,1.606209,4.626733,None,2024-02-29T16:06:41.017+01:00,1993,1993-01-01T00:00:00+01:00,1993-12-31T00:00:00+01:00,children
1,665160,NCD_BMI_PLUS2C,COUNTRY,TUR,YEAR,EUR,Europe,SEX,2008,SEX_MLE,...,8.7 [5.5-12.7],8.704282,5.491283,12.714332,None,2024-02-29T16:06:41.017+01:00,2008,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00,children
2,665226,NCD_BMI_PLUS2C,COUNTRY,GHA,YEAR,AFR,Africa,SEX,2013,SEX_FMLE,...,4.3 [3.1-5.6],4.291492,3.121873,5.612285,None,2024-02-29T16:06:41.017+01:00,2013,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00,children
3,665505,NCD_BMI_PLUS2C,COUNTRY,CIV,YEAR,AFR,Africa,SEX,2011,SEX_FMLE,...,2.6 [0.6-7.0],2.632850,0.577861,6.967106,None,2024-02-29T16:06:41.017+01:00,2011,2011-01-01T00:00:00+01:00,2011-12-31T00:00:00+01:00,children
4,665861,NCD_BMI_PLUS2C,GLOBAL,GLOBAL,YEAR,None,None,SEX,2008,SEX_FMLE,...,4.7 [4.4-5.0],4.700040,4.443568,4.981692,None,2024-05-23T13:28:38.2+02:00,2008,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00,children

FOR MALNUTRITION

In [ ]:
import requests

url="https://ghoapi.azureedge.net/api/NCD_BMI_18C"

response=requests.get(url)

data = response.json()

In [ ]:
data.keys()

dict_keys(['@odata.context', 'value'])

In [ ]:
import pandas as pd
df = pd.DataFrame(data['value'])

df.head()

,Id,IndicatorCode,SpatialDimType,SpatialDim,ParentLocationCode,TimeDimType,ParentLocation,Dim1Type,Dim1,TimeDim,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,664857,NCD_BMI_18C,COUNTRY,OMN,EMR,YEAR,Eastern Mediterranean,SEX,SEX_FMLE,2002,...,None,7.9 [6.3-9.6],7.858858,6.286396,9.569392,None,2024-02-29T16:06:41.017+01:00,2002,2002-01-01T00:00:00+01:00,2002-12-31T00:00:00+01:00
1,665305,NCD_BMI_18C,COUNTRY,CHN,WPR,YEAR,Western Pacific,SEX,SEX_MLE,1997,...,None,8.0 [7.1-9.0],8.034202,7.129874,9.015918,None,2024-02-29T16:06:41.017+01:00,1997,1997-01-01T00:00:00+01:00,1997-12-31T00:00:00+01:00
2,666501,NCD_BMI_18C,COUNTRY,DEU,EUR,YEAR,Europe,SEX,SEX_FMLE,2012,...,None,1.9 [1.4-2.5],1.892521,1.407323,2.489300,None,2024-02-29T16:06:41.017+01:00,2012,2012-01-01T00:00:00+01:00,2012-12-31T00:00:00+01:00
3,667044,NCD_BMI_18C,COUNTRY,BIH,EUR,YEAR,Europe,SEX,SEX_FMLE,2018,...,None,2.9 [1.3-5.2],2.913355,1.341783,5.157771,None,2024-02-29T16:06:41.017+01:00,2018,2018-01-01T00:00:00+01:00,2018-12-31T00:00:00+01:00
4,667745,NCD_BMI_18C,COUNTRY,RWA,AFR,YEAR,Africa,SEX,SEX_BTSX,2003,...,None,10.3 [8.4-12.4],10.297140,8.377061,12.396117,None,2024-02-29T16:06:41.017+01:00,2003,2003-01-01T00:00:00+01:00,2003-12-31T00:00:00+01:00

In [ ]:
df.shape

(20790, 25)

In [ ]:
df['age_group']="adults"

In [ ]:
df.head()

,Id,IndicatorCode,SpatialDimType,SpatialDim,ParentLocationCode,TimeDimType,ParentLocation,Dim1Type,Dim1,TimeDim,...,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd,age_group
0,664857,NCD_BMI_18C,COUNTRY,OMN,EMR,YEAR,Eastern Mediterranean,SEX,SEX_FMLE,2002,...,7.9 [6.3-9.6],7.858858,6.286396,9.569392,None,2024-02-29T16:06:41.017+01:00,2002,2002-01-01T00:00:00+01:00,2002-12-31T00:00:00+01:00,adults
1,665305,NCD_BMI_18C,COUNTRY,CHN,WPR,YEAR,Western Pacific,SEX,SEX_MLE,1997,...,8.0 [7.1-9.0],8.034202,7.129874,9.015918,None,2024-02-29T16:06:41.017+01:00,1997,1997-01-01T00:00:00+01:00,1997-12-31T00:00:00+01:00,adults
2,666501,NCD_BMI_18C,COUNTRY,DEU,EUR,YEAR,Europe,SEX,SEX_FMLE,2012,...,1.9 [1.4-2.5],1.892521,1.407323,2.489300,None,2024-02-29T16:06:41.017+01:00,2012,2012-01-01T00:00:00+01:00,2012-12-31T00:00:00+01:00,adults
3,667044,NCD_BMI_18C,COUNTRY,BIH,EUR,YEAR,Europe,SEX,SEX_FMLE,2018,...,2.9 [1.3-5.2],2.913355,1.341783,5.157771,None,2024-02-29T16:06:41.017+01:00,2018,2018-01-01T00:00:00+01:00,2018-12-31T00:00:00+01:00,adults
4,667745,NCD_BMI_18C,COUNTRY,RWA,AFR,YEAR,Africa,SEX,SEX_BTSX,2003,...,10.3 [8.4-12.4],10.297140,8.377061,12.396117,None,2024-02-29T16:06:41.017+01:00,2003,2003-01-01T00:00:00+01:00,2003-12-31T00:00:00+01:00,adults

In [ ]:
import requests

url="https://ghoapi.azureedge.net/api/NCD_BMI_MINUS2C"

response=requests.get(url)

data = response.json()

In [ ]:
data.keys()

In [ ]:
import pandas as pd

df=pd.DataFrame(data['value'])

df.head()

In [ ]:
df['age_group'] = "Children"

In [ ]:
df.head()

In [ ]:
# Define a dictionary of URLs
urls = {
    'obesity_adults': "https://ghoapi.azureedge.net/api/NCD_BMI_30C",
    'obesity_children': "https://ghoapi.azureedge.net/api/NCD_BMI_PLUS2C",
    'malnutrition_adults': "https://ghoapi.azureedge.net/api/NCD_BMI_18C",
    'malnutrition_children': "https://ghoapi.azureedge.net/api/NCD_BMI_MINUS2C"
}

# Fetch data and create DataFrames
df_obesity_adults = pd.DataFrame(requests.get(urls['obesity_adults']).json()['value'])
df_obesity_adults['age_group'] = 'adults'

df_obesity_children = pd.DataFrame(requests.get(urls['obesity_children']).json()['value'])
df_obesity_children['age_group'] = 'children'

df_malnutrition_adults = pd.DataFrame(requests.get(urls['malnutrition_adults']).json()['value'])
df_malnutrition_adults['age_group'] = 'adults'

df_malnutrition_children = pd.DataFrame(requests.get(urls['malnutrition_children']).json()['value'])
df_malnutrition_children['age_group'] = 'children'

# Display the head of each DataFrame to verify
print("Obesity Adults:")
display(df_obesity_adults.head())
print("\nObesity Children:")
display(df_obesity_children.head())
print("\nMalnutrition Adults:")
display(df_malnutrition_adults.head())
print("\nMalnutrition Children:")
display(df_malnutrition_children.head())

In [ ]:
# Combine obesity datasets
df_obesity = pd.concat([df_obesity_adults, df_obesity_children], ignore_index=True)

# Combine malnutrition datasets
df_malnutrition = pd.concat([df_malnutrition_adults, df_malnutrition_children], ignore_index=True)

# Convert 'TimeDim' to int for filtering
df_obesity['TimeDim'] = df_obesity['TimeDim'].astype(int)
df_malnutrition['TimeDim'] = df_malnutrition['TimeDim'].astype(int)

# Filter data between 2012 and 2022 inclusive
df_obesity = df_obesity[(df_obesity['TimeDim'] >= 2012) & (df_obesity['TimeDim'] <= 2022)]
df_malnutrition = df_malnutrition[(df_malnutrition['TimeDim'] >= 2012) & (df_malnutrition['TimeDim'] <= 2022)]

# Quick check
print("Filtered Obesity Data:")
display(df_obesity.head())

print("Filtered Malnutrition Data:")
display(df_malnutrition.head())

In [ ]:
# Define the columns to keep
columns_to_keep = ['ParentLocation', 'Dim1', 'TimeDim', 'Low', 'High', 'NumericValue', 'SpatialDim', 'age_group']

# Keep only the selected columns in both datasets
df_obesity = df_obesity[columns_to_keep]
df_malnutrition = df_malnutrition[columns_to_keep]

# Display heads for verification
print("Cleaned Obesity Dataset:")
print(df_obesity.head())

print("\nCleaned Malnutrition Dataset:")
print(df_malnutrition.head())

In [ ]:
df_obesity.rename(columns={
    'TimeDim': 'Year',
    'Dim1': 'Gender',
    'NumericValue': 'Mean_Estimate',
    'Low': 'LowerBound',
    'High': 'UpperBound',
    'ParentLocation': 'Region',
    'SpatialDim': 'Country'
}, inplace=True)

df_malnutrition.rename(columns={
    'TimeDim': 'Year',
    'Dim1': 'Gender',
    'NumericValue': 'Mean_Estimate',
    'Low': 'LowerBound',
    'High': 'UpperBound',
    'ParentLocation': 'Region',
    'SpatialDim': 'Country'
}, inplace=True)

In [ ]:
# Define gender mapping
gender_mapping = {
    'SEX_MLE': 'Male',
    'SEX_FMLE': 'Female',
    'SEX_BTSX': 'Both'
}

# Apply mapping to both datasets
df_obesity['Gender'] = df_obesity['Gender'].map(gender_mapping)
df_malnutrition['Gender'] = df_malnutrition['Gender'].map(gender_mapping)

In [ ]:
print(df_obesity.head())
print(df_malnutrition.head())

In [ ]:

!pip install pycountry

# Import libraries
import pandas as pd
import pycountry
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Function to convert ISO Alpha-3 codes to full country names
def get_country_name(code):
    try:
        return pycountry.countries.get(alpha_3=code).name
    except:
        # Return None if code is not found
        return None

# Dictionary for special WHO/World Bank codes
special_cases = {
    'GLOBAL': 'Global',
    'WB_LMI': 'Low & Middle Income',
    'WB_HI': 'High Income',
    'WB_LI': 'Low Income',
    'EMR': 'Eastern Mediterranean Region',
    'EUR': 'Europe',
    'AFR': 'Africa',
    'SEAR': 'South-East Asia Region',
    'WPR': 'Western Pacific Region',
    'AMR': 'Americas Region',
    'WB_UMI': 'Upper Middle Income'
}

# Apply function to convert country codes
def convert_country_code(code):
    name = get_country_name(code)
    if name:
        return name
    else:
        return special_cases.get(code, code)  # default to original if not found

# Apply the function to convert country codes in both dataframes
df_obesity['Country'] = df_obesity['Country'].apply(convert_country_code)
df_malnutrition['Country'] = df_malnutrition['Country'].apply(convert_country_code)

Let's start by visualizing the obesity rates across different countries, genders, and age groups over the years.

In [ ]:
# Visualize obesity rates by year and gender
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_obesity, x='Year', y='Mean_Estimate', hue='Gender', errorbar='sd')
plt.title('Obesity Rates Over Time by Gender')
plt.ylabel('Mean Obesity Rate')
plt.grid(True)
plt.show()

# Visualize obesity rates by year and age group
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_obesity, x='Year', y='Mean_Estimate', hue='age_group', errorbar='sd')
plt.title('Obesity Rates Over Time by Age Group')
plt.ylabel('Mean Obesity Rate')
plt.grid(True)
plt.show()

# Visualize obesity rates by region
plt.figure(figsize=(14, 7))
sns.barplot(data=df_obesity, x='Region', y='Mean_Estimate', errorbar='sd')
plt.title('Mean Obesity Rate by Region (2012-2022)')
plt.ylabel('Mean Obesity Rate')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

Let's compare the obesity and malnutrition rates to see how they differ across age groups and genders.

In [ ]:
# Combine obesity and malnutrition data for comparison
df_obesity['condition'] = 'Obesity'
df_malnutrition['condition'] = 'Malnutrition'
df_combined = pd.concat([df_obesity, df_malnutrition], ignore_index=True)

# Visualize combined data by age group
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_combined, x='Year', y='Mean_Estimate', hue='condition', style='age_group', errorbar='sd')
plt.title('Obesity vs Malnutrition Rates Over Time by Age Group')
plt.ylabel('Mean Rate')
plt.grid(True)
plt.show()

# Visualize combined data by gender
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_combined, x='Year', y='Mean_Estimate', hue='condition', style='Gender', errorbar='sd')
plt.title('Obesity vs Malnutrition Rates Over Time by Gender')
plt.ylabel('Mean Rate')
plt.grid(True)
plt.show()

# Visualize combined data by region
plt.figure(figsize=(14, 7))
sns.barplot(data=df_combined, x='Region', y='Mean_Estimate', hue='condition', errorbar='sd')
plt.title('Mean Obesity vs Malnutrition Rate by Region (2012-2022)')
plt.ylabel('Mean Rate')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

## Summary of Findings

Based on the visualizations of obesity and malnutrition rates from 2012 to 2022:

### Obesity Trends

*   **Overall Trend:** Obesity rates generally show an increasing trend over the years for both adults and children.
*   **Age Group Comparison:** Adults consistently have significantly higher obesity rates compared to children. The gap between adult and child obesity rates appears to be widening over time.
*   **Gender Comparison:** For adults, the obesity rates for males and females are relatively similar and follow a similar increasing trend. For children, the obesity rates for both genders are also similar, but at a much lower level than adults.
*   **Regional Comparison:** The mean obesity rates vary by region. The Western Pacific and Americas regions appear to have higher mean obesity rates compared to other regions like Africa and South-East Asia.

### Malnutrition Trends

*   **Overall Trend:** Malnutrition rates show a general decreasing trend over the years for both adults and children, although the changes are less pronounced than the increase in obesity.
*   **Age Group Comparison:** Malnutrition rates are generally higher in children compared to adults, although the difference is not as large as the difference in obesity rates between age groups.
*   **Gender Comparison:** Malnutrition rates are relatively similar for males and females across both age groups.
*   **Regional Comparison:** Malnutrition rates also vary by region. South-East Asia and Africa appear to have higher mean malnutrition rates compared to other regions like Europe and the Americas.

### Obesity vs Malnutrition Comparison

*   Obesity rates are generally higher than malnutrition rates across all age groups, genders, and regions in the 2012-2022 period.
*   The gap between obesity and malnutrition rates is particularly large for adults.
*   While obesity rates are increasing and malnutrition rates are decreasing, both remain significant public health concerns in different populations and regions.

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect('nutrition_analysis.db')
cursor = conn.cursor()

# Create tables
cursor.execute('''
CREATE TABLE IF NOT EXISTS obesity (
    Year INTEGER,
    Gender TEXT,
    Mean_Estimate REAL,
    LowerBound REAL,
    UpperBound REAL,
    age_group TEXT,
    Country TEXT,
    Region TEXT,
    CI_Width REAL,
    Obesity_Level TEXT
)
''')

cursor.execute('''
CREATE TABLE IF NOT EXISTS malnutrition (
    Year INTEGER,
    Gender TEXT,
    Mean_Estimate REAL,
    LowerBound REAL,
    UpperBound REAL,
    age_group TEXT,
    Country TEXT,
    Region TEXT,
    CI_Width REAL,
    Malnutrition_Level TEXT
)
''')

# Calculate CI_Width and add placeholder columns
df_obesity['CI_Width'] = df_obesity['UpperBound'] - df_obesity['LowerBound']
df_obesity['Obesity_Level'] = None  # Placeholder

df_malnutrition['CI_Width'] = df_malnutrition['UpperBound'] - df_malnutrition['LowerBound']
df_malnutrition['Malnutrition_Level'] = None # Placeholder


# Insert into obesity
for _, row in df_obesity.iterrows():
    cursor.execute('''
    INSERT INTO obesity VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ''', (
        row['Year'], row['Gender'], row['Mean_Estimate'], row['LowerBound'], row['UpperBound'],
        row['age_group'], row['Country'], row['Region'], row['CI_Width'], row['Obesity_Level']
    ))

# Insert into malnutrition
for _, row in df_malnutrition.iterrows():
    cursor.execute('''
    INSERT INTO malnutrition VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ''', (
        row['Year'], row['Gender'], row['Mean_Estimate'], row['LowerBound'], row['UpperBound'],
        row['age_group'], row['Country'], row['Region'], row['CI_Width'], row['Malnutrition_Level']
    ))

conn.commit()
conn.close()

In [ ]:
conn = sqlite3.connect('nutrition_analysis.db')
cursor = conn.cursor()

# 1. Top 5 regions with highest avg obesity in 2022
print("1. Top 5 regions with highest avg obesity in 2022:")
cursor.execute('''
SELECT Region, AVG(Mean_Estimate) AS Avg_Obesity
FROM obesity
WHERE Year = 2022
GROUP BY Region
ORDER BY Avg_Obesity DESC
LIMIT 5;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 2. Top 5 countries with highest obesity estimates
print("2. Top 5 countries with highest obesity estimates:")
cursor.execute('''
SELECT Country, MAX(Mean_Estimate) AS Max_Obesity
FROM obesity
GROUP BY Country
ORDER BY Max_Obesity DESC
LIMIT 5;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 3. Obesity trend in India
print("3. Obesity trend in India:")
cursor.execute('''
SELECT Year, AVG(Mean_Estimate) AS Avg_Obesity
FROM obesity
WHERE Country = 'India'
GROUP BY Year
ORDER BY Year;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)


# 4. Average obesity by gender
print("4. Average obesity by gender:")
cursor.execute('''
SELECT Gender, AVG(Mean_Estimate) AS Avg_Obesity
FROM obesity
GROUP BY Gender;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 5. Country count by obesity level & age group - Note: Obesity_Level is None in current data
print("5. Country count by obesity level & age group:")
cursor.execute('''
SELECT Obesity_Level, age_group, COUNT(DISTINCT Country) AS Country_Count
FROM obesity
GROUP BY Obesity_Level, age_group;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 6. Top 5 least reliable & top 5 most consistent countries (CI_Width)
# Least reliable
print("6. Top 5 least reliable countries (highest Avg_CI):")
cursor.execute('''
SELECT Country, AVG(CI_Width) AS Avg_CI
FROM obesity
GROUP BY Country
ORDER BY Avg_CI DESC
LIMIT 5;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# Most consistent
print("Top 5 most consistent countries (lowest Avg_CI):")
cursor.execute('''
SELECT Country, AVG(CI_Width) AS Avg_CI
FROM obesity
GROUP BY Country
ORDER BY Avg_CI ASC
LIMIT 5;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 7. Average obesity by age group
print("7. Average obesity by age group:")
cursor.execute('''
SELECT age_group, AVG(Mean_Estimate) AS Avg_Obesity
FROM obesity
GROUP BY age_group;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 8. Top 10 countries with consistently low obesity
print("8. Top 10 countries with consistently low obesity:")
cursor.execute('''
SELECT Country, AVG(Mean_Estimate) AS Avg_Obesity, AVG(CI_Width) AS Avg_CI
FROM obesity
GROUP BY Country
HAVING Avg_Obesity < 25 AND Avg_CI < 3
ORDER BY Avg_Obesity ASC
LIMIT 10;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 9. Countries where female obesity > male obesity by large margin (same year)
print("9. Countries where female obesity > male obesity by large margin (same year):")
cursor.execute('''
SELECT o1.Country, o1.Year, o1.Mean_Estimate AS Female_Obesity, o2.Mean_Estimate AS Male_Obesity,
       (o1.Mean_Estimate - o2.Mean_Estimate) AS Difference
FROM obesity o1
JOIN obesity o2 ON o1.Country = o2.Country AND o1.Year = o2.Year
WHERE o1.Gender = 'Female' AND o2.Gender = 'Male'
AND (o1.Mean_Estimate - o2.Mean_Estimate) > 5;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 10. Global average obesity per year
print("10. Global average obesity per year:")
cursor.execute('''
SELECT Year, AVG(Mean_Estimate) AS Global_Obesity_Avg
FROM obesity
GROUP BY Year
ORDER BY Year;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

conn.close()

In [ ]:
conn = sqlite3.connect('nutrition_analysis.db')
cursor = conn.cursor()

# 1. Obesity vs Malnutrition comparison by country (example: top 5)
print("1. Obesity vs Malnutrition comparison by country (example: top 5):")
cursor.execute('''
SELECT o.Country,
       AVG(o.Mean_Estimate) AS Avg_Obesity,
       AVG(m.Mean_Estimate) AS Avg_Malnutrition
FROM obesity o
JOIN malnutrition m ON o.Country = m.Country AND o.Year = m.Year
GROUP BY o.Country
ORDER BY Avg_Obesity DESC
LIMIT 5;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 2. Gender-based disparity in both
print("2. Gender-based disparity in both:")
cursor.execute('''
SELECT o.Gender,
       AVG(o.Mean_Estimate) AS Obesity,
       AVG(m.Mean_Estimate) AS Malnutrition
FROM obesity o
JOIN malnutrition m ON o.Gender = m.Gender AND o.Year = m.Year
GROUP BY o.Gender;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 3. Region-wise avg (Africa and America)
print("3. Region-wise avg (Africa and America):")
cursor.execute('''
SELECT o.Region,
       AVG(o.Mean_Estimate) AS Avg_Obesity,
       AVG(m.Mean_Estimate) AS Avg_Malnutrition
FROM obesity o
JOIN malnutrition m ON o.Region = m.Region AND o.Year = m.Year
WHERE o.Region IN ('Africa', 'Americas Region')
GROUP BY o.Region;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 4. Countries with rising obesity + falling malnutrition
print("4. Countries with rising obesity + falling malnutrition:")
cursor.execute('''
SELECT o.Country,
       MAX(o.Mean_Estimate) - MIN(o.Mean_Estimate) AS Obesity_Increase,
       MIN(m.Mean_Estimate) - MAX(m.Mean_Estimate) AS Malnutrition_Decrease
FROM obesity o
JOIN malnutrition m ON o.Country = m.Country AND o.Year = m.Year
GROUP BY o.Country
HAVING Obesity_Increase > 5 AND Malnutrition_Decrease < 0;
''')

# 5. Age-wise trend analysis
print("5. Age-wise trend analysis:")
cursor.execute('''
SELECT o.age_group,
       AVG(o.Mean_Estimate) AS Avg_Obesity,
       AVG(m.Mean_Estimate) AS Avg_Malnutrition
FROM obesity o
JOIN malnutrition m
    ON o.age_group = m.age_group
    AND o.Year = m.Year
GROUP BY o.age_group
ORDER BY o.age_group;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

In [ ]:
conn = sqlite3.connect('nutrition_analysis.db')
cursor = conn.cursor()

# 1. Avg malnutrition by age group
print("1. Avg malnutrition by age group:")
cursor.execute('''
SELECT age_group, AVG(Mean_Estimate) AS Avg_Malnutrition
FROM malnutrition
GROUP BY age_group;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 2. Top 5 countries with highest malnutrition
print("2. Top 5 countries with highest malnutrition:")
cursor.execute('''
SELECT Country, MAX(Mean_Estimate) AS Max_Malnutrition
FROM malnutrition
GROUP BY Country
ORDER BY Max_Malnutrition DESC
LIMIT 5;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 3. Malnutrition trend in Africa
print("3. Malnutrition trend in Africa:")
cursor.execute('''
SELECT Year, AVG(Mean_Estimate) AS Avg_Malnutrition
FROM malnutrition
WHERE Region = 'Africa'
GROUP BY Year
ORDER BY Year;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 4. Gender-based average malnutrition
print("4. Gender-based average malnutrition:")
cursor.execute('''
SELECT Gender, AVG(Mean_Estimate) AS Avg_Malnutrition
FROM malnutrition
GROUP BY Gender;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 5. Malnutrition level-wise CI_Width by age group
print("5. Malnutrition level-wise CI_Width by age group:")
cursor.execute('''
SELECT Malnutrition_Level, age_group, AVG(CI_Width) AS Avg_CI
FROM malnutrition
GROUP BY Malnutrition_Level, age_group;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 6. Yearly change in India, Nigeria, Brazil
print("6. Yearly change in India, Nigeria, Brazil:")
cursor.execute('''
SELECT Country, Year, AVG(Mean_Estimate) AS Avg_Malnutrition
FROM malnutrition
WHERE Country IN ('India', 'Nigeria', 'Brazil')
GROUP BY Country, Year
ORDER BY Country, Year;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 7. Regions with lowest malnutrition avg
print("7. Regions with lowest malnutrition avg:")
cursor.execute('''
SELECT Region, AVG(Mean_Estimate) AS Avg_Malnutrition
FROM malnutrition
GROUP BY Region
ORDER BY Avg_Malnutrition ASC
LIMIT 5;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 8. Countries with increasing malnutrition
print("8. Countries with increasing malnutrition:")
cursor.execute('''
SELECT Country,
       MIN(Mean_Estimate) AS Min_Value,
       MAX(Mean_Estimate) AS Max_Value
FROM malnutrition
GROUP BY Country
HAVING MAX(Mean_Estimate) - MIN(Mean_Estimate) > 5
ORDER BY (Max_Value - Min_Value) DESC;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 9. Min/Max malnutrition levels year-wise
print("9. Min/Max malnutrition levels year-wise:")
cursor.execute('''
SELECT Year,
       MIN(Mean_Estimate) AS Min_Level,
       MAX(Mean_Estimate) AS Max_Level
FROM malnutrition
GROUP BY Year
ORDER BY Year;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

# 10. Countries with CI_Width > 5
print("10. Countries with CI_Width > 5:")
cursor.execute('''
SELECT Country, Year, CI_Width
FROM malnutrition
WHERE CI_Width > 5
ORDER BY CI_Width DESC;
''')
results = cursor.fetchall()
for row in results:
    print(row)
print("-" * 20)

conn.close()

In [ ]:
import sqlite3
import pandas as pd

# Connect to SQLite database
conn = sqlite3.connect('nutrition_analysis.db')

# Export obesity table
df_obesity = pd.read_sql_query("SELECT * FROM obesity", conn)
df_obesity.to_csv("obesity_data.csv", index=False)
print("✅ Exported obesity_data.csv")

# Export malnutrition table
df_malnutrition = pd.read_sql_query("SELECT * FROM malnutrition", conn)
df_malnutrition.to_csv("malnutrition_data.csv", index=False)
print("✅ Exported malnutrition_data.csv")

# Close connection
conn.close()

In [ ]:
!pip install streamlit plotly

In [ ]:
import streamlit as st

In [87]:
import pandas as pd
import sqlite3
import plotly.express as px
import streamlit as st

# Title
st.title("🌍 Global Obesity & Malnutrition Dashboard")

# Connect to DB
conn = sqlite3.connect('nutrition_analysis.db')

# Load data
df_obesity = pd.read_sql_query("SELECT * FROM obesity", conn)
df_malnutrition = pd.read_sql_query("SELECT * FROM malnutrition", conn)

# Merge for joint analysis
df_combined = pd.merge(df_obesity, df_malnutrition,
                       on=['Country', 'Year', 'Gender', 'age_group'],
                       suffixes=('_obesity', '_malnutrition'))

# Sidebar Filters
st.sidebar.header("Filter Data")
selected_country = st.sidebar.selectbox("Select Country", sorted(df_combined['Country'].unique()))
selected_year = st.sidebar.slider("Select Year",
                                   int(df_combined['Year'].min()),
                                   int(df_combined['Year'].max()),
                                   step=1)

# Filtered Data
filtered_data = df_combined[(df_combined['Country'] == selected_country) &
                            (df_combined['Year'] == selected_year)]

# Section 1: Country Overview
st.subheader(f"📌 {selected_country} - Year {selected_year}")

col1, col2 = st.columns(2)

with col1:
    st.metric("Avg Obesity (%)", round(filtered_data['Mean_Estimate_obesity'].mean(), 2))

with col2:
    st.metric("Avg Malnutrition (%)", round(filtered_data['Mean_Estimate_malnutrition'].mean(), 2))

# Section 2: Gender Comparison
st.subheader("🔍 Gender Comparison")
gender_plot = px.bar(filtered_data, x='Gender',
                     y=['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition'],
                     barmode='group',
                     labels={"value": "Estimate (%)", "variable": "Indicator"},
                     title="Obesity vs Malnutrition by Gender")
st.plotly_chart(gender_plot)

# Section 3: Age-wise Comparison
st.subheader("📊 Age-wise Trend")
age_plot = px.line(filtered_data, x='age_group',
                   y=['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition'],
                   labels={"value": "Estimate (%)", "variable": "Indicator"},
                   title="Obesity & Malnutrition by Age Group")
st.plotly_chart(age_plot)

# Section 4: Global Scatter
st.subheader("🌐 Global Obesity vs Malnutrition (All Countries)")

avg_global = df_combined.groupby("Country")[['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition']].mean().reset_index()

scatter = px.scatter(avg_global, x='Mean_Estimate_obesity', y='Mean_Estimate_malnutrition',
                     hover_name='Country',
                     labels={"Mean_Estimate_obesity": "Obesity (%)", "Mean_Estimate_malnutrition": "Malnutrition (%)"},
                     title="Obesity vs Malnutrition - Country-wise Comparison")
st.plotly_chart(scatter)

# Countries where Obesity Increased and Malnutrition Decreased
st.subheader("Countries where Obesity Increased and Malnutrition Decreased")

change_df = df_combined.groupby('Country').agg(
    obesity_min=('Mean_Estimate_obesity', 'min'),
    obesity_max=('Mean_Estimate_obesity', 'max'),
    malnutrition_min=('Mean_Estimate_malnutrition', 'min'),
    malnutrition_max=('Mean_Estimate_malnutrition', 'max')
).reset_index()

change_df['obesity_diff'] = change_df['obesity_max'] - change_df['obesity_min']
change_df['malnutrition_diff'] = change_df['malnutrition_max'] - change_df['malnutrition_min']

trend_df = change_df[
    (change_df['obesity_diff'] > 0) &
    (change_df['malnutrition_diff'] < 0)
].sort_values(by='obesity_diff', ascending=False)

st.table(trend_df[['Country', 'obesity_diff', 'malnutrition_diff']].head(10))

# Region-wise Comparison (Obesity vs Malnutrition)
st.subheader("Region-wise Obesity vs Malnutrition Averages")

region_avg = filtered_data.groupby('Region_obesity')[['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition']].mean().reset_index()

fig_region = px.bar(
    region_avg, x='Region_obesity', y=['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition'],
    barmode='group',
    labels={'value': 'Average (%)', 'Region_obesity': 'Region', 'variable': 'Indicator'},
    title='Average Obesity vs Malnutrition by Region'
)
st.plotly_chart(fig_region, use_container_width=True)


# Close DB connection
conn.close()

2025-09-20 06:50:11.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:11.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:11.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:11.994 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:11.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:11.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.157 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.158 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.160 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.165 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.167 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.168 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.169 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.217 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.246 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.309 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.310 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-20 06:50:12.312 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
import streamlit as st

In [104]:

conn = sqlite3.connect('nutrition_analysis.db')

# Load data
df_obesity = pd.read_sql_query("SELECT * FROM obesity", conn)
df_malnutrition = pd.read_sql_query("SELECT * FROM malnutrition", conn)

# ✅ Drop Region to avoid Region_obesity and Region_malnutrition
df_obesity = df_obesity.drop(columns=['Region'], errors='ignore')
df_malnutrition = df_malnutrition.drop(columns=['Region'], errors='ignore')

# ✅ Rename conflicting column before merge
df_obesity = df_obesity.rename(columns={"Mean_Estimate": "Mean_Estimate_obesity"})
df_malnutrition = df_malnutrition.rename(columns={"Mean_Estimate": "Mean_Estimate_malnutrition"})


# Merge for joint analysis
df_combined = pd.merge(df_obesity, df_malnutrition,
                       on=['Country', 'Year', 'Gender', 'age_group'])


# ✅ ADD REGION MAPPING AFTER MERGE
# 🔧 ADDED unified Region column mapping (after merge)
region_map = {
    'United States': 'North America',
    'Canada': 'North America',
    'Brazil': 'South America',
    'Argentina': 'South America',
    'Germany': 'Europe',
    'France': 'Europe',
    'Nigeria': 'Africa',
    'Kenya': 'Africa',
    'India': 'Asia',
    'China': 'Asia',
    'Australia': 'Oceania',
    'Japan': 'Asia',
    'Mexico': 'North America',
    # Add more countries as needed
}
df_combined['Region'] = df_combined['Country'].map(region_map)

In [114]:
%%writefile NutritionParadox.py

import streamlit as st
import pandas as pd
import sqlite3
import plotly.express as px

# Title
st.title("🌍 Global Obesity & Malnutrition Dashboard")

# Connect to DB
conn = sqlite3.connect('nutrition_analysis.db')

# Load data
df_obesity = pd.read_sql_query("SELECT * FROM obesity", conn)
df_malnutrition = pd.read_sql_query("SELECT * FROM malnutrition", conn)

# ✅ Drop Region to avoid Region_obesity and Region_malnutrition
df_obesity = df_obesity.drop(columns=['Region'], errors='ignore')
df_malnutrition = df_malnutrition.drop(columns=['Region'], errors='ignore')

# ✅ Rename conflicting column before merge
df_obesity = df_obesity.rename(columns={"Mean_Estimate": "Mean_Estimate_obesity"})
df_malnutrition = df_malnutrition.rename(columns={"Mean_Estimate": "Mean_Estimate_malnutrition"})


# Merge for joint analysis
df_combined = pd.merge(df_obesity, df_malnutrition,
                       on=['Country', 'Year', 'Gender', 'age_group'])


# ✅ ADD REGION MAPPING AFTER MERGE
# 🔧 ADDED unified Region column mapping (after merge)
region_map = {
    'United States': 'North America',
    'Canada': 'North America',
    'Brazil': 'South America',
    'Argentina': 'South America',
    'Germany': 'Europe',
    'France': 'Europe',
    'Nigeria': 'Africa',
    'Kenya': 'Africa',
    'India': 'Asia',
    'China': 'Asia',
    'Australia': 'Oceania',
    'Japan': 'Asia',
    'Mexico': 'North America',
    # Add more countries as needed
}
df_combined['Region'] = df_combined['Country'].map(region_map)




# Sidebar Filters
st.sidebar.header("Filter Data")
selected_country = st.sidebar.selectbox("Select Country", sorted(df_combined['Country'].unique()))
selected_year = st.sidebar.slider("Select Year",
                                   int(df_combined['Year'].min()),
                                   int(df_combined['Year'].max()),
                                   step=1)

# Filtered Data
filtered_data = df_combined[(df_combined['Country'] == selected_country) &
                            (df_combined['Year'] == selected_year)]

# Section 1: Country Overview
st.subheader(f"📌 {selected_country} - Year {selected_year}")

col1, col2 = st.columns(2)

with col1:
    st.metric("Avg Obesity (%)", round(filtered_data['Mean_Estimate_obesity'].mean(), 2))

with col2:
    st.metric("Avg Malnutrition (%)", round(filtered_data['Mean_Estimate_malnutrition'].mean(), 2))

# Section 2: Gender Comparison
st.subheader("🔍 Gender Comparison")
gender_plot = px.bar(filtered_data, x='Gender',
                     y=['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition'],
                     barmode='group',
                     labels={"value": "Estimate (%)", "variable": "Indicator"},
                     title="Obesity vs Malnutrition by Gender")
st.plotly_chart(gender_plot)

# Section 3: Age-wise Comparison
st.subheader("📊 Age-wise Trend")
age_plot = px.line(filtered_data, x='age_group',
                   y=['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition'],
                   labels={"value": "Estimate (%)", "variable": "Indicator"},
                   title="Obesity & Malnutrition by Age Group")
st.plotly_chart(age_plot)

# Section 4: Global Scatter
st.subheader("🌐 Global Obesity vs Malnutrition (All Countries)")

avg_global = df_combined.groupby("Country")[['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition']].mean().reset_index()

scatter = px.scatter(avg_global, x='Mean_Estimate_obesity', y='Mean_Estimate_malnutrition',
                     hover_name='Country',
                     labels={"Mean_Estimate_obesity": "Obesity (%)", "Mean_Estimate_malnutrition": "Malnutrition (%)"},
                     title="Obesity vs Malnutrition - Country-wise Comparison")
st.plotly_chart(scatter)

# Countries where Obesity
st.subheader("Countries where Obesity Increased and Malnutrition Decreased")

change_df = df_combined.groupby('Country').agg(
    obesity_min=('Mean_Estimate_obesity', 'min'),
    obesity_max=('Mean_Estimate_obesity', 'max'),
    malnutrition_min=('Mean_Estimate_malnutrition', 'min'),
    malnutrition_max=('Mean_Estimate_malnutrition', 'max')
).reset_index()

change_df['obesity_diff'] = change_df['obesity_max'] - change_df['obesity_min']
change_df['malnutrition_diff'] = change_df['malnutrition_max'] - change_df['malnutrition_min']


trend_df = change_df[change_df['obesity_diff']>change_df['malnutrition_diff']]


st.table(trend_df[['Country', 'obesity_diff', 'malnutrition_diff']].head(10))

# Region-wise Comparison (Obesity vs Malnutrition)
st.subheader("Region-wise Obesity vs Malnutrition Averages")

region_avg = df_combined.dropna(subset=['Region']).groupby('Region')[['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition']].mean().reset_index()


fig_region = px.bar(
    region_avg, x='Region', y=['Mean_Estimate_obesity', 'Mean_Estimate_malnutrition'],
    barmode='group',
    labels={'value': 'Average (%)', 'Region': 'Region', 'variable': 'Indicator'},
    title='Average Obesity vs Malnutrition by Region'
)
st.plotly_chart(fig_region, use_container_width=True)


# Close DB connection
conn.close()

Overwriting NutritionParadox.py

In [115]:
# @title Setup code
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

--2025-09-20 07:30:34--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2025.9.0/cloudflared-linux-amd64 [following]
--2025-09-20 07:30:34--  https://github.com/cloudflare/cloudflared/releases/download/2025.9.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/732846a2-353e-405f-af4b-b5cfa6b6ca42?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-09-20T08%3A14%3A23Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-09-20T07%3A14%3A20Z&ske=2025-09-20T08%3A14%3A23Z&sks=b&skv=2018-11-09&sig=UEkCom8q9jf1MnJCI4sDUhcohgkmVA6e1oHeoBD8PvY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1ODM1MzczNCwibmJmIjoxNzU4MzUzNDM0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.ZQ6tvHgKmg1ctD3erSJsxPMeAoJ9ZPpxr6FCq-czR4Q&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2025-09-20 07:30:34--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/732846a2-353e-405f-af4b-b5cfa6b6ca42?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-09-20T08%3A14%3A23Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-09-20T07%3A14%3A20Z&ske=2025-09-20T08%3A14%3A23Z&sks=b&skv=2018-11-09&sig=UEkCom8q9jf1MnJCI4sDUhcohgkmVA6e1oHeoBD8PvY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1ODM1MzczNCwibmJmIjoxNzU4MzUzNDM0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.ZQ6tvHgKmg1ctD3erSJsxPMeAoJ9ZPpxr6FCq-czR4Q&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41192366 (39M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64.11’

cloudflared-linux-a 100%[===================>]  39.28M  --.-KB/s    in 0.1s

2025-09-20 07:30:35 (263 MB/s) - ‘cloudflared-linux-amd64.11’ saved [41192366/41192366]

nohup: appending output to 'nohup.out'

In [116]:
!streamlit run /content/NutritionParadox.py &>/content/logs.txt &

In [117]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://dsc-encouraging-argue-promo.trycloudflare.com